apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres:9.6
---
kind: Deployment
metadata:
  name: myfrontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: adminer
        image: adminer
---
kind: Service
metadata:
  name: db-in
spec:
  selector:
    app: db
  ports:
  - port: 80
    targetPort: 80
---
kind: Service
metadata:
  name: inbound
spec:
  type: NodePort
  selector:
      app: frontend
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 33333
