apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres:9.6
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: env-configs
                key: POSTGRES_USER
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: env-configs
                key: POSTGRES_DB
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfrontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: adminer
        image: adminer
---
apiVersion: v1
kind: Service
metadata:
  name: db-in
spec:
  selector:
    app: db
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: inbound
spec:
  type: NodePort
  selector:
      app: frontend
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
