version: '3.7'    

services:
  mydb:
    image: postgres:9.6
    networks:
      - demonet    

  frontend:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - demonet    

networks:
  demonet:
