version: "3.7"

services:
  target:
    image: training/whoami
    networks:
      - demonet
    deploy:
      replicas: 3

  probe:
    image: centos:7
    command: ["sleep", "10000"]
    networks:
      - demonet

networks:
  demonet:
