kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-demo
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/billmills/demo/mystore"
