apiVersion: apps/v1
kind: Deployment
metadata:
  name: voldemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: sleepy
        image: centos:7
        command: ["sleep", "10000"]
